#!bin/bash
#==================================
DIR="${0%/*}"
source "$DIR/utils"
source "$DIR/clone_repo"
#===================================
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -d | --debug )
    debug=1
    ;;
  -ct | --clone-template )
    clone_template
    exit 0
    ;;
  -h | --help | * )
    help
    exit 0
    ;;
esac; shift; done
